[features]
seeds = false
skip-lint = false
[programs.localnet]
program = "2PHLJwx7Tp2L5CJPZfreVPZQnhgT9D6PwvMdGAn6pHRb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kunalbagaria/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
