name: Daily Compatibility Test

on:
  push:

  schedule:
    # This is scheduled to run every day at midnight
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Setup Environment
      run: |
        sudo apt update
        sudo apt install -y pkg-config build-essential libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang cmake make libprotobuf-dev protobuf-compiler
        cargo install cargo-edit --force

    - name: Update Anchor Lang and Anchor SPL Packages
      run: |
        cargo-upgrade upgrade --package anchor-lang
        cargo-upgrade upgrade --package anchor-spl

    - name: Install AVM and Latest Anchor CLI
      run: |
        cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
        avm install latest
        avm use latest

    - name: Install beta Solana CLI
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/beta/install)"
        echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

    - name: Generate Keypair File and Update Anchor.toml
      run: |
        solana-keygen new --outfile /home/runner/keypair.json --no-bip39-passphrase --force
        cat /home/runner/keypair.json
        sed -i 's|wallet = ".*"|wallet = "/home/runner/keypair.json"|' Anchor.toml
        cat Anchor.toml

    - name: Start Test Validator and Airdrop SOL
      run: |
        solana-test-validator &
        sleep 15
        solana airdrop 100000 --keypair /home/runner/keypair.json --url http://localhost:8899

    - name: Test project with latest Anchor version and beta Solana Tools
      run : |
        solana --version

        cargo clean
        anchor build
        anchor deploy

    - name: Test project with latest Anchor version and stable Solana Tools
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
        echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

        solana --version

        anchor build
        anchor deploy

    - name: Test project with master Anchor version and stable Solana Tools
      run: |
        git clone https://github.com/coral-xyz/anchor.git
        cd anchor/cli
        cargo build --release
        cd ../..

        cargo clean
        ./anchor/target/release/anchor build
        ./anchor/target/release/anchor deploy

    - name: Test project with latest Anchor version and master branch Solana Tools
      run: |
        echo -e '\nsolana-program = { git = "https://github.com/solana-labs/solana.git", branch = "master" }' >> ./programs/program/Cargo.toml

        cargo clean
        anchor build
        anchor deploy